services:
  kratos-migrate:
    image: oryd/kratos:v25.4.0
    command:
      - migrate
      - sql
      - --yes
      - mysql://root@tcp(127.0.0.1:4000)/kratos?clientFoundRows=true&multiStatements=true&parseTime=true

    environment:
      DSN: mysql://root@tcp(127.0.0.1:4000)/kratos?clientFoundRows=true&multiStatements=true&parseTime=true
    network_mode: host
    restart: "no"

  kratos:
    image: oryd/kratos:v25.4.0
    command:
      - serve
      - --config
      - /etc/config/kratos/kratos.yml
    volumes:
      - ./contrib/quickstart/kratos/email-password/kratos.yml:/etc/config/kratos/kratos.yml:ro
      - ./contrib/quickstart/kratos/email-password/identity.schema.json:/etc/config/kratos/identity.schema.json:ro
    environment:
      DSN: mysql://root@tcp(127.0.0.1:4000)/kratos?clientFoundRows=true&multiStatements=true&parseTime=true
    network_mode: host
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully