services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: kratos
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: kratos
      MYSQL_ROOT_PASSWORD: supersecret
    command:
      - --sql-mode=TRADITIONAL
    volumes:
      - mysqldbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=supersecret"]
      interval: 5s
      timeout: 5s
      retries: 5

  kratos-migrate:
    image: oryd/kratos:v25.4.0
    command:
      - migrate
      - sql
      - mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
      - --yes
    environment:
      DSN: mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  kratos:
    image: oryd/kratos:v25.4.0
    command:
      - serve
      - --config
      - /etc/config/kratos/kratos.yml
    volumes:
      - ./contrib/quickstart/kratos/email-password/kratos.yml:/etc/config/kratos/kratos.yml:ro
      - ./contrib/quickstart/kratos/email-password/identity.schema.json:/etc/config/kratos/identity.schema.json:ro
    environment:
      DSN: mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
    ports:
      - "4433:4433"
      - "4434:4434"
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully

volumes:
  mysqldbdata:
